export interface Product {
  id: string;
  name: string;
  price: number;
  image: string;
  category: "men" | "women";
  material: string;
  weight: string;
  fit: string;
  sizes: string[];
}

export const products: Product[] = [
  {
    id: "m1",
    name: "Supima Cotton Crew Tee",
    price: 19.90,
    image: "/assets/product-tee-navy.jpg",
    category: "men",
    material: "100% Supima Cotton",
    weight: "200gsm",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "m2",
    name: "Essential White Tee",
    price: 14.90,
    image: "/assets/product-tee-white.jpg",
    category: "men",
    material: "100% Cotton",
    weight: "180gsm",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "m3",
    name: "Stretch Slim Chino",
    price: 39.90,
    image: "/assets/product-chino-black.jpg",
    category: "men",
    material: "98% Cotton, 2% Elastane",
    weight: "280gsm",
    fit: "Slim",
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "m4",
    name: "Dry Sweat Pullover Hoodie",
    price: 29.90,
    image: "/assets/product-hoodie-gray.jpg",
    category: "men",
    material: "100% Polyester",
    weight: "340gsm",
    fit: "Boxy",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "m5",
    name: "Linen Blend Shirt",
    price: 34.90,
    image: "/assets/product-shirt-beige.jpg",
    category: "men",
    material: "55% Linen, 45% Cotton",
    weight: "160gsm",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "m6",
    name: "MA-1 Bomber Jacket",
    price: 59.90,
    image: "/assets/product-jacket-olive.jpg",
    category: "men",
    material: "100% Nylon",
    weight: "220gsm",
    fit: "Regular",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "w1",
    name: "Merino Blend Crew Sweater",
    price: 49.90,
    image: "/assets/product-sweater-cream.jpg",
    category: "women",
    material: "70% Wool, 30% Polyester",
    weight: "260gsm",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "w2",
    name: "Wide Leg Trousers",
    price: 39.90,
    image: "/assets/product-trousers-navy.jpg",
    category: "women",
    material: "95% Polyester, 5% Elastane",
    weight: "240gsm",
    fit: "Wide",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "w3",
    name: "Supima Cotton V-Neck Tee",
    price: 19.90,
    image: "/assets/product-tee-white.jpg",
    category: "women",
    material: "100% Supima Cotton",
    weight: "180gsm",
    fit: "Fitted",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "w4",
    name: "Ultra Light Down Jacket",
    price: 69.90,
    image: "/assets/product-jacket-olive.jpg",
    category: "women",
    material: "100% Nylon, Down Fill",
    weight: "120gsm",
    fit: "Regular",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "w5",
    name: "Linen Relaxed Shirt",
    price: 34.90,
    image: "/assets/product-shirt-beige.jpg",
    category: "women",
    material: "100% Linen",
    weight: "150gsm",
    fit: "Oversized",
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "w6",
    name: "Dry Stretch Hoodie",
    price: 29.90,
    image: "/assets/product-hoodie-gray.jpg",
    category: "women",
    material: "100% Polyester",
    weight: "300gsm",
    fit: "Relaxed",
    sizes: ["XS", "S", "M", "L"],
  },
];